CREATE TABLE IF NOT EXISTS users (
	uID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL,
	email VARCHAR(128) NOT NULL,
	fName VARCHAR(30) NOT NULL,
	lName VARCHAR(30) NOT NULL,
	role varchar(30) DEFAULT 'default',
	reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	verification varchar(7) NOT NULL,
	status varchar(15) NOT NULL DEFAULT 'locked');